test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,10 +1,14 @@
 name: Update Frontend on Strapi API Change
+
 on:
-  schedule:
-    - cron: "*/5 * * * *"
+  workflow_run:
+    workflows: ["Check Strapi API for Changes"]
+    types:
+      - completed
 
 jobs:
   update-frontend:
+    if: github.event.workflow_run.conclusion == 'success'
     runs-on: ubuntu-latest
 
     steps:
@@ -14,17 +18,26 @@ jobs:
     - name: Check Strapi API for Changes
       run: |
         curl -s http://83.166.147.249:1337/api/accueil?populate=* > current_response.json
-        if diff -q current_response.json previous_response.json > /dev/null; then
-          echo "No changes in the Strapi API."
-          exit 0
+        if [ $? -eq 0 ]; then
+          if [ -f previous_response.json ]; then
+            if ! cmp -s current_response.json previous_response.json; then
+              echo "Changes detected in the Strapi API. Updating frontend..."
+              git config --local user.email "actions@github.com"
+              git config --local user.name "GitHub Actions"
+              git add .
+              git commit -m "Update frontend on Strapi API change"
+              git push --quiet --set-upstream origin ${{ github.head_ref }}
+              mv current_response.json previous_response.json
+            else
+              echo "No changes in the Strapi API."
+            fi
+          else
+            echo "No previous response file found. Assuming initial run."
+            mv current_response.json previous_response.json
+          fi
         else
-          echo "Changes detected in the Strapi API. Updating frontend..."
-          git config --local user.email "actions@github.com"
-          git config --local user.name "GitHub Actions"
-          git add .
-          git commit -m "Update frontend on Strapi API change"
-          git push --quiet --set-upstream origin ${{ github.head_ref }}
+          echo "Error: Unable to fetch Strapi API data."
+          exit 1
         fi
-        mv current_response.json previous_response.json
       env:
         GH_PAT: ${{ secrets.GH_PAT }}
